### ISSUE TITLE
ckeditor not working properly

### ISSUE THREAD

**Issue by IgnacyFluder** [DogukanUrker/flaskBlog#10]
**Describe the bug**
I cant upload any images using the ckeditor nor can i add images using a url

**To Reproduce**
Open the post creation menu then click on the image icon

**Expected behavior**
image gets uploaded and shown in the textbox

**Desktop (please complete the following information):**

- OS: Linux mint 
- Browser Firefox
- 115

**Comment by AntonioDiTuri** [comment]
Same problem here media uploader not working

**Comment by DogukanUrker** [comment]
Fixed. #21
