### ISSUE TITLE
code snippets markup is not working 

### ISSUE THREAD

**Issue by wishrohitv** [DogukanUrker/flaskBlog#106]
**Describe the bug**
while adding code snippets it is not working as expected 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/57f803e0-7b9d-4baf-88c8-877a8bd4c4a5)

**Desktop (please complete the following information):**

- OS: linux
- Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DogukanUrker** [comment]
https://github.com/user-attachments/assets/82a613bd-bd89-46b7-91bb-522d6a9341e9

Sorry but I don't see any problem here. Can you please be more specific?

**Comment by wishrohitv** [comment]
sorry for ignorance, i did'nt see in dropdown menu, i thought `code view` toggle is button to add code snippets, i really sorry

**Comment by DogukanUrker** [comment]
> sorry for ignorance, i did'nt see in dropdown menu, i thought `code view` toggle is button to add code snippets, i really sorry

No problem, have a good day. 💜
