### ISSUE TITLE
Upgrade Flask-WTF to 1.2.1

### ISSUE THREAD

**Issue by edwinlock** [DogukanUrker/flaskBlog#22]
After cloning the repository and installing the requirements (in a virtual environment), running `python app.py` gives me the error "ImportError: cannot import name 'Markup' from 'flask'". Updating Flask-WTF in requirements.txt to 1.2.1 fixes the issue.

**Comment by DogukanUrker** [comment]
Fixed, thank you 💜.
[Commit](https://github.com/DogukanUrker/flaskBlog/commit/2d7410cb7cfb01369d4d6ac17e1297fc900db83c)
