### ISSUE TITLE
How to access the admin panel?

### ISSUE THREAD

**Issue by pradeepkumarjha0** [DogukanUrker/flaskBlog#23]
Everything is working fine. How to go to the admin panel to assign 'admin' and 'user' roles to new users?

**Comment by DogukanUrker** [comment]
> Everything is working fine. How to go to the admin panel to assign 'admin' and 'user' roles to new users?

When you create new user, the role sets to “user” by default. You can’t set your account role to admin from user. There is 2 different ways to set a user role to admin. The first way is open users.db and set user role to admin. The second way is login to “DogukanUrker” account which is admin by default. After that you should go to admin/users page, you can see all users here and you can change roles.

**Comment by DogukanUrker** [comment]
I am going to add a future for creating admin account by default today.

**Comment by pradeepkumarjha0** [comment]
Thank you for your time.

**Comment by pradeepkumarjha0** [comment]
I do not see the solution. Where does the user get the option to be admin?

**Comment by DogukanUrker** [comment]
Normal user can't set his account role to admin from user. Only can admins change user roles. 

You need to login to default admin account.

Username: admin
Password: admin

I recommend watching this video from 4:21

https://youtu.be/BTBXe6yPbLE?si=Fm89svORbL6q4nRD

**Comment by DogukanUrker** [comment]
> I am going to add a future for creating admin account by default today.

I thought this idea but It can be dangerous for app security.
