### ISSUE TITLE
[bug] Change old article

### ISSUE THREAD

**Issue by dkashkarev** [DogukanUrker/flaskBlog#28]
![image](https://github.com/DogukanUrker/flaskBlog/assets/67013355/1e5d8f4b-7909-42a9-98d9-65cd60537daa)

**Comment by DogukanUrker** [comment]
Please explain more. How and where did this happen?

**Comment by dkashkarev** [comment]
> Please explain more. How and where did this happen?
Hi,
Create post => Ok
Change post title or other element = > error

**Comment by dkashkarev** [comment]
This error only appears if there is a photo in the post
![image](https://github.com/DogukanUrker/flaskBlog/assets/67013355/5bbb7951-4b77-43e8-87b3-427560718358)

**Comment by DogukanUrker** [comment]
Thank you for your feedback 💜.
[Fixed](https://github.com/DogukanUrker/flaskBlog/commit/987d3d88179a128a3501064d85f2a6e94ab01dd3)
