### ISSUE TITLE
Add preview and description for post card

### ISSUE THREAD

**Issue by dkashkarev** [DogukanUrker/flaskBlog#32]
the text and photo from the editor look bad, let's add a short description and preview, it is advisable to insert the preview on the post page, thank

**Comment by DogukanUrker** [comment]
When you say it looks bad, are you talking about the text and image overflow?

**Comment by dkashkarev** [comment]
> When you say it looks bad, are you talking about the text and image overflow?

There is a beautiful standard card with a photo title and a brief description

**Comment by DogukanUrker** [comment]
That sounds very nice. I will make it and it will be released with the next version of flaskBlog (probably in a few weeks). Thank you for your contribution to flaskBlog.💜

**Comment by dkashkarev** [comment]
> That sounds very nice. I will make it and it will be released with the next version of flaskBlog (probably in a few weeks). Thank you for your contribution to flaskBlog.💜

Can you make me a contributor and create an style-alt brunch for me? I've already rewritten the styles (css) for my fork several times. I can help, plz

**Comment by DogukanUrker** [comment]
> > That sounds very nice. I will make it and it will be released with the next version of flaskBlog (probably in a few weeks). Thank you for your contribution to flaskBlog.💜
> 
> Can you make me a contributor and create an style-alt brunch for me? I've already rewritten the styles (css) for my fork several times. I can help, plz

Please accept my invitation from this [link](https://github.com/DogukanUrker/flaskBlog/invitations).

**Comment by DogukanUrker** [comment]
Please make your changes only in templates/[standardUI](https://github.com/DogukanUrker/flaskBlog/tree/style-alt/templates/standardUI) and static/[standardUI](https://github.com/DogukanUrker/flaskBlog/tree/style-alt/static/standardUI). Do not modify tailwindUI folders/files. Thanks. 🙏🏻@dkashkarev

**Comment by dkashkarev** [comment]
> Please make your changes only in templates/[standardUI](https://github.com/DogukanUrker/flaskBlog/tree/style-alt/templates/standardUI) and static/[standardUI](https://github.com/DogukanUrker/flaskBlog/tree/style-alt/static/standardUI). Do not modify tailwindUI folders/files. Thanks. 🙏🏻@dkashkarev

Ok. May be you use a telegram, add me plz

**Comment by dkashkarev** [comment]
https://t.me/dkashkarev
